# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-26 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangle', '0002_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u6b63\u6587')),
            ],
            options={
                'verbose_name': 'ABOUT',
                'verbose_name_plural': 'ABOUT',
            },
        ),
    ]
