# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-26 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pangle', '0003_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '\u5173\u4e8e', 'verbose_name_plural': '\u5173\u4e8e'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '\u535a\u6587', 'verbose_name_plural': '\u535a\u6587'},
        ),
        migrations.AlterModelOptions(
            name='download',
            options={'verbose_name': '\u8d44\u6e90\u4e0b\u8f7d', 'verbose_name_plural': '\u8d44\u6e90\u4e0b\u8f7d'},
        ),
    ]
