# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-26 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pangle', '0004_auto_20180726_1450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
